org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.208
loader_version_range=[1,)

## Mod Properties

mod_id=create_frequency
mod_name=Create Frequency
mod_license=MIT
mod_version=0.5.0
mod_group_id=dev.ripiters.create_frequency

create_version = 6.0.8-169
create_version_range = [6.0.8,)
ponder_version = 1.0.66
flywheel_version = 1.0.5
registrate_version = MC1.21-1.3.0+62
mixin_extras_version = 0.4.1
jei_version = 19.21.0.247
